### ISSUE TITLE
Usage questions offline mode

### ISSUE THREAD

**Issue by fvisticot** [hurshi/dio-http-cache#2]
Can you please detail in the documentation how is managed the case when no network is available ? Is there an error or the data is returned by the cache ?

**Comment by hurshi** [comment]
### Hi, fvisticot
Thanks for your questions.
I have written an example in [README](https://github.com/hurshi/dio-http-cache#example-for-maxage-and-maxstale), please let me know if you still have confusion.

###  Example for maxAge and maxStale

```dart
_dio.post(
	"https://www.exmaple.com",
	data: {'k': "keyword"},
  options:buildCacheOptions(
  	Duration(days: 3), 
  	maxStale: Duration(days: 7), 
  )
)
```

1. 0 ~ 3 days : Return data from cache directly (irrelevant with network).
2. 3 ~ 7 days: 
   1. Get data from network first.
   2. If getting data from network succeeds, refresh cache.
   3. If getting data from network fails or no network avaliable, get data from cache instead of an error.
3. 7 ~ ∞ days: It won't use cache anymore, and the cache will be deleted at the right time.

**Comment by JCKodel** [comment]
Scenario: 
When online, read always from network and cache result.
When offline, read from cache.

Code:
`buildCacheOptions(Duration.zero, maxStale: Duration(days: 30))`

Is this right?

**Comment by hurshi** [comment]
@JCKodel  Yes, that's right.
