### ISSUE TITLE
[Question] forceRefresh on config object ?

### ISSUE THREAD

**Issue by fvisticot** [hurshi/dio-http-cache#38]
I would like to use this option as "defaultConfig"
buildCacheOptions(Duration(days: 7), forceRefresh: true)

I do not see the forceRefresh property in the CacheConfig object ?
Is it possible or do we need to buildCacheOption for each request requiring forceRefresh to true ?

**Comment by hurshi** [comment]
Hi, Thanks for your issue.
I don’t understand what scenario you have created such a demand, if you need to forceRefresh every time, why use this library?
I guess you want to get fresh data every time, but if you disconnect from the Internet, you can get the old data instead of reporting an error, if so, you can use buildCacheOptions(Duration(days: 0)) to achieve it.
Anyway, welcome to discuss here 😄
